### ISSUE TITLE
Adding context support to Client

### ISSUE THREAD

**Issue by rickycraft** [antoninbas/p4runtime-go-client#19]
Right now when creating a Client is required a stopCh to manage proper cleanup of the goroutine.
`func (c *Client) Run(stopCh <-chan struct{},arbitrationCh chan<- bool,messageCh chan<- *p4_v1.StreamMessageResponse)`
I'm new to go, but from what i've seen substituting it with context.Context is a more stardard way to do it. It should be a minor change.

**Comment by antoninbas** [comment]
If the context is only used for cancellation then there is no difference IMO. The context is a more complex object.
I'm used to working with Kubernetes libraries, which typically use a channel for this (stopping a long-running goroutine).
However, other functions in the client (the ones which initiate an RPC call) should definitely have a context parameter.

**Comment by rickycraft** [comment]
Sidenote, are you planning to create the interfaces for reading/setting registers?

**Comment by rickycraft** [comment]
Sidenote, are you planning
