### ISSUE TITLE
Feature request in updating pipeline config

### ISSUE THREAD

**Issue by rickycraft** [antoninbas/p4runtime-go-client#21]
It would be nice to have the ability to set a different type of PipelineConfigRequest for example VERIFY_AND_SAVE.

https://github.com/antoninbas/p4runtime-go-client/blob/e8fa35a5aa8beb23e90bd9b58f2d5b4f971a442d/pkg/client/fwd_pipe.go#L38

For reference here's the [link ](https://github.com/alsadiamir/ulissep4controller/blob/config-swap/controller/pkg/client/fwd_pipe.go)to the changes i've made.

**Comment by antoninbas** [comment]
Do you want to open a PR with the necessary changes?
