### ISSUE TITLE
Packet-out using P4Runtime Client?

### ISSUE THREAD

**Issue by gcgirish** [antoninbas/p4runtime-go-client#33]
The `streamSendCh` isn't exposed to the P4runtime client application. See the `Client` struct below.
```shell
type Client struct {
	ClientOptions
	p4_v1.P4RuntimeClient
	deviceID     uint64
	electionID   p4_v1.Uint128
	p4Info       *p4_config_v1.P4Info
	role         *p4_v1.Role
	streamSendCh chan *p4_v1.StreamMessageRequest
}
```
Should we expose a new API, for instance `SendMessage`, in `client.go` for the client application to send packet-outs or other messages?
Something like below...

```shell
func (c *Client) SendMessage(msg *p4_v1.StreamMessageRequest) {
        c.streamSendCh <- msg:
}
```

**Comment by antoninbas** [comment]
That sounds reasonable to me.
Perhaps in addition to a generic method like the one your propose, we could also have a more specialized method to send packet-out messages specifically:
```go
func (c *Client) SendPacketOut(ctx context.Context, pkt *p4_v1.PacketOut) error
```

It would be consistent with how digests are acked:
https://github.com/antoninbas/p4runtime-go-client/blob/54febd69c5c7b89acf43072045f6e5d9a7f05032/pkg/client/digests.go#L9

**Comment by gcgirish** [comment]
Thanks for the quick response. I will submit a patch soon.
